---
# Install docker engine:
# https://docs.docker.com/engine/install/ubuntu/
- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools' ]

- name: Add docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ vm_distro }} stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name={{ item }} state=latest
  loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io' ]

# Add root user to docker user group
- name: Add default user to docker group
  ansible.builtin.user:
    name: "{{ vm_user }}"
    groups: docker
    append: yes

# Install docker module:
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html
- name: Install docker module for Python
  pip:
    name: docker