---
# Pull the docker image created in the previous stage onto host
# https://docs.ansible.com/ansible/2.8/modules/docker_image_module.html 
- name: Pull docker image
  docker_image:
    name: "nginx"
    source: pull

# Create docker container and run the container
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#ansible-collections-community-docker-docker-container-module
- name: Create container
  docker_container:
    name: "nginx"
    image: "nginx"
    state: started
    container_default_behavior: no_defaults
    purge_networks: yes
    networks_cli_compatible: yes
    network_mode: host